var carcolor1 = " Blue";
var carcolor2 = " Red";
var num1 = 1;
var num2 = 7;
console.log("hello my name is" + carcolor1);
console.log(carcolor2);
console.log(carcolor1+carcolor2);
console.log(num1);
console.log(num1+num2);
console.log(num1 == 7);
console.log(num2==7);
console.log(carcolor1 + num2);
console.log(typeof (carcolor1+num2));
console.log(typeof (num2+carcolor1));
var char = 'a';
console.log(typeof char);
